import pandas as pd
import csv
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.image as mpimg
import numpy as np



df1 = pd.read_csv('InCeptionResNethistoryFold1.csv')
df2 = pd.read_csv('InCeptionResNethistoryFold2.csv')
df3 = pd.read_csv('InCeptionResNethistoryFold3.csv')
df4 = pd.read_csv('InCeptionResNethistoryFold4.csv')
df5 = pd.read_csv('InCeptionResNethistoryFold5.csv')
df6 = pd.read_csv('InCeptionResNethistoryFold6.csv')
df7 = pd.read_csv('InCeptionResNethistoryFold7.csv')
df8 = pd.read_csv('InCeptionResNethistoryFold8.csv')
df9 = pd.read_csv('InCeptionResNethistoryFold9.csv')
df10 = pd.read_csv('InCeptionResNethistoryFold10.csv')

N = np.arange(0, 70)

plt.figure()
plt.plot(N,df1['accuracy'], label = "Fold 1")
plt.plot(N,df2['accuracy'], label = "Fold 2")
plt.plot(N,df3['accuracy'], label = "Fold 3")
plt.plot(N,df4['accuracy'], label = "Fold 4")
plt.plot(N,df5['accuracy'], label = "Fold 5")
plt.plot(N,df6['accuracy'], label = "Fold 6")
plt.plot(N,df7['accuracy'], label = "Fold 7")
plt.plot(N,df8['accuracy'], label = "Fold 8")
plt.plot(N,df9['accuracy'], label = "Fold 9")
plt.plot(N,df10['accuracy'], label = "Fold 10")
plt.xlabel("Num of Epochs")
plt.ylabel("Accuracy")
plt.yscale('linear')
plt.xscale('linear')
plt.title("InceptionResNet v2 \n \n"
          "Training Accuracy")
plt.tight_layout()
plt.grid(True, color='w', linestyle='-')
plt.gca().patch.set_facecolor('lightgrey')
plt.legend()
plt.savefig('Train_Acc.png')
plt.show()

plt.figure()
plt.plot(N,df1['val_accuracy'], label = "Fold 1")
plt.plot(N,df2['val_accuracy'], label = "Fold 2")
plt.plot(N,df3['val_accuracy'], label = "Fold 3")
plt.plot(N,df4['val_accuracy'], label = "Fold 4")
plt.plot(N,df5['val_accuracy'], label = "Fold 5")
plt.plot(N,df6['val_accuracy'], label = "Fold 6")
plt.plot(N,df7['val_accuracy'], label = "Fold 7")
plt.plot(N,df8['val_accuracy'], label = "Fold 8")
plt.plot(N,df9['val_accuracy'], label = "Fold 9")
plt.plot(N,df10['val_accuracy'], label = "Fold 10")
plt.xlabel("Num of Epochs")
plt.ylabel("Accuracy")
plt.yscale('linear')
plt.xscale('linear')
plt.title("InceptionResNet v2 \n \n"
          "Validation Accuracy")
plt.tight_layout()
plt.grid(True, color='w', linestyle='-')
plt.gca().patch.set_facecolor('lightgrey')
plt.legend()
plt.savefig('Val_Acc.png')
plt.show()

plt.figure()
plt.plot(N,df1['loss'], label = "Fold 1")
plt.plot(N,df2['loss'], label = "Fold 2")
plt.plot(N,df3['loss'], label = "Fold 3")
plt.plot(N,df4['loss'], label = "Fold 4")
plt.plot(N,df5['loss'], label = "Fold 5")
plt.plot(N,df6['loss'], label = "Fold 6")
plt.plot(N,df7['loss'], label = "Fold 7")
plt.plot(N,df8['loss'], label = "Fold 8")
plt.plot(N,df9['loss'], label = "Fold 9")
plt.plot(N,df10['loss'], label = "Fold 10")
plt.xlabel("Num of Epochs")
plt.ylabel("Loss")
plt.yscale('linear')
plt.xscale('linear')
plt.title("InceptionResNet v2 \n \n"
          "Training Loss")
plt.tight_layout()
plt.grid(True, color='w', linestyle='-')
plt.gca().patch.set_facecolor('lightgrey')
plt.legend()
plt.savefig('Train_Loss.png')
plt.show()

plt.figure()
plt.plot(N,df1['val_loss'], label = "Fold 1")
plt.plot(N,df2['val_loss'], label = "Fold 2")
plt.plot(N,df3['val_loss'], label = "Fold 3")
plt.plot(N,df4['val_loss'], label = "Fold 4")
plt.plot(N,df5['val_loss'], label = "Fold 5")
plt.plot(N,df6['val_loss'], label = "Fold 6")
plt.plot(N,df7['val_loss'], label = "Fold 7")
plt.plot(N,df8['val_loss'], label = "Fold 8")
plt.plot(N,df9['val_loss'], label = "Fold 9")
plt.plot(N,df10['val_loss'], label = "Fold 10")
plt.xlabel("Num of Epochs")
plt.ylabel("Loss")
plt.yscale('linear')
plt.xscale('linear')
plt.title("InceptionResNet v2 \n \n"
          "Validation Loss")
plt.tight_layout()
plt.grid(True, color='w', linestyle='-')
plt.gca().patch.set_facecolor('lightgrey')
plt.legend()
plt.savefig('Val_Loss.png')
plt.show()
